# Generated by Django 4.2.11 on 2024-03-27 08:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resident_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RoomAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='room',
            name='resident',
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
        migrations.DeleteModel(
            name='Resident',
        ),
        migrations.AddField(
            model_name='roomavailability',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room_app.room'),
        ),
        migrations.AddField(
            model_name='bookingroom',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room_app.room'),
        ),
        migrations.AddField(
            model_name='bookingroom',
            name='room_availability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room_app.roomavailability'),
        ),
    ]
